/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.foss.llamas.poker;

import com.foss.llamas.poker.domain.game.RoundInterface;

public class Game {
	
	public void acceptCommand(String string) {
		
	}
	
	private RoundInterface currentRound = null;
}
