/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.foss.llamas.poker;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Game classUnderTest = new Game();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
