/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chat.llamas.cardlogic.game.impl;

import com.beust.jcommander.JCommander;

import chat.llamas.cardlogic.GameEventManagerInterface;
import chat.llamas.cardlogic.GameInterface;
import chat.llamas.cardlogic.RoundInterface;
import chat.llamas.cardlogic.domain.ArgumentTokenizer;
import chat.llamas.cardlogic.domain.GameState;
import chat.llamas.cardlogic.domain.commands.BetCommand;
import chat.llamas.cardlogic.domain.commands.CallCommand;
import chat.llamas.cardlogic.domain.commands.CancelGameCommand;
import chat.llamas.cardlogic.domain.commands.CheckCommand;
import chat.llamas.cardlogic.domain.commands.FoldCommand;
import chat.llamas.cardlogic.domain.commands.JoinGameCommand;
import chat.llamas.cardlogic.domain.commands.LeaveGameCommand;
import chat.llamas.cardlogic.domain.commands.MuckCommand;
import chat.llamas.cardlogic.domain.commands.RaiseCommand;
import chat.llamas.cardlogic.domain.commands.ShowCommand;
import chat.llamas.cardlogic.domain.commands.StartGameCommand;
import chat.llamas.cardlogic.domain.commands.ViewCardsCommand;
import chat.llamas.cardlogic.domain.game.Player;

public class Game implements GameInterface {
	
	
	public static void main(String[] args) {
		Game game = new Game();
		
		game.acceptCommand("startgame --player=joe --joker-count=2");
	}
	private GameState gameState = GameState.INACTIVE;
	
	public void acceptCommand(String string) {
		
		String[] argv = ArgumentTokenizer.tokenize(string).toArray(String[]::new);
		
		// Game Commands
		StartGameCommand startGameCommand = new StartGameCommand();
		CancelGameCommand cancelGameCommand = new CancelGameCommand();
		JoinGameCommand joinGameCommand = new JoinGameCommand();
		LeaveGameCommand leaveGameCommand = new LeaveGameCommand();
		
		// Round Commands
		FoldCommand foldCommand = new FoldCommand();
		MuckCommand muckCommand = new MuckCommand();
		ShowCommand showCommand = new ShowCommand();
		CallCommand callCommand = new CallCommand();
		RaiseCommand raiseCommand = new RaiseCommand();
		BetCommand betCommand = new BetCommand();
		CheckCommand checkCommand = new CheckCommand();
		ViewCardsCommand viewCardsCommand = new ViewCardsCommand();
		
		// Admin Commands
		// TODO: Add here.
		
		JCommander jc = JCommander.newBuilder()
				.addCommand(startGameCommand)
				.addCommand(cancelGameCommand)
				.addCommand(joinGameCommand)
				.addCommand(leaveGameCommand)
				.addCommand(foldCommand)
				.addCommand(muckCommand)
				.addCommand(showCommand)
				.addCommand(callCommand)
				.addCommand(raiseCommand)
				.addCommand(betCommand)
				.addCommand(checkCommand)
				.addCommand(viewCardsCommand)
			  .build();
			jc.parse(argv);
		System.out.println( jc.getParsedCommand() );
		System.out.println(startGameCommand.getJokerCount());
	}
	
	private RoundInterface currentRound = null;

	@Override
	public RoundInterface getCurrentRound() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public GameState getGameState() {
		return gameState;
	}

	@Override
	public GameEventManagerInterface getGameEventManager() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Player getStartingPlayer() {
		// TODO Auto-generated method stub
		return null;
	}

}
